export const GET_LEAVES_REQUEST = "GET_LEAVES_REQUEST";
export const GET_LEAVES_SUCCESS = "GET_LEAVES_SUCCESS";
export const GET_LEAVES_FAIL = "GET_LEAVES_FAIL";

export const GET_TEAM_LEAVES_REQUEST = "GET_TEAM_LEAVES_REQUEST";
export const GET_TEAM_LEAVES_SUCCESS = "GET_TEAM_LEAVES_SUCCESS";
export const GET_TEAM_LEAVES_FAIL = "GET_TEAM_LEAVES_FAIL";

export const GET_ALL_TEAM_LEAVES_REQUEST = "GET_ALL_TEAM_LEAVES_REQUEST";
export const GET_ALL_TEAM_LEAVES_SUCCESS = "GET_ALL_TEAM_LEAVES_SUCCESS";
export const GET_ALL_TEAM_LEAVES_FAIL = "GET_ALL_TEAM_LEAVES_FAIL";

export const GET_TEAM_LEAVES_GROUP_BY_MONTH_REQUEST = "GET_TEAM_LEAVES_GROUP_BY_MONTH_REQUEST";
export const GET_TEAM_LEAVES_GROUP_BY_MONTH_SUCCESS = "GET_TEAM_LEAVES_GROUP_BY_MONTH_SUCCESS";
export const GET_TEAM_LEAVES_GROUP_BY_MONTH_FAIL = "GET_TEAM_LEAVES_GROUP_BY_MONTH_FAIL";

export const GET_ALL_TEAM_LEAVES_GROUP_BY_MONTH_REQUEST =
  "GET_ALL_TEAM_LEAVES_GROUP_BY_MONTH_REQUEST";
export const GET_ALL_TEAM_LEAVES_GROUP_BY_MONTH_SUCCESS =
  "GET_ALL_TEAM_LEAVES_GROUP_BY_MONTH_SUCCESS";
export const GET_ALL_TEAM_LEAVES_GROUP_BY_MONTH_FAIL = "GET_ALL_TEAM_LEAVES_GROUP_BY_MONTH_FAIL";

export const SUBMIT_LEAVE_REQUEST = "SUBMIT_LEAVE_REQUEST";
export const SUBMIT_LEAVE_SUCCESS = "SUBMIT_LEAVE_SUCCESS";
export const SUBMIT_LEAVE_FAIL = "SUBMIT_LEAVE_FAIL";

export const REMOVE_LEAVE_BY_ID_REQUEST = "REMOVE_LEAVE_BY_ID_REQUEST";
export const REMOVE_LEAVE_BY_ID_SUCCESS = "REMOVE_LEAVE_BY_ID_SUCCESS";
export const REMOVE_LEAVE_BY_ID_FAIL = "REMOVE_LEAVE_BY_ID_FAIL";

export const GET_LEAVE_BY_ID_REQUEST = "GET_LEAVE_BY_ID_REQUEST";
export const GET_LEAVE_BY_ID_SUCCESS = "GET_LEAVE_BY_ID_SUCCESS";
export const GET_LEAVE_BY_ID_FAIL = "GET_LEAVE_BY_ID_FAIL";
export const GET_LEVE_BY_ID_RESET = "GET_LEVE_BY_ID_RESET";

export const UPDATE_LEAVE_BY_ID_REQUEST = "UPDATE_LEAVE_BY_ID_REQUEST";
export const UPDATE_LEAVE_BY_ID_SUCCESS = "UPDATE_LEAVE_BY_ID_SUCCESS";
export const UPDATE_LEAVE_BY_ID_FAIL = "UPDATE_LEAVE_BY_ID_FAIL";
export const UPDATE_LEAVE_BY_ID_RESET = "UPDATE_LEAVE_BY_ID_RESET";
