export const GET_TEAMS_REQUEST = "GET_TEAMS_REQUEST";
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS";
export const GET_TEAMS_FAIL = "GET_TEAMS_FAIL";

export const ADD_TEAM_REQUEST = "ADD_TEAM_REQUEST";
export const ADD_TEAM_SUCCESS = "ADD_TEAM_SUCCESS";
export const ADD_TEAM_FAIL = "ADD_TEAM_FAIL";

export const DELETE_TEAM_BY_ID_REQUEST = "DELETE_TEAM_BY_ID_REQUEST";
export const DELETE_TEAM_BY_ID_SUCCESS = "DELETE_TEAM_BY_ID_SUCCESS";
export const DELETE_TEAM_BY_ID_FAIL = "DELETE_TEAM_BY_ID_FAIL";

export const GET_TEAM_BY_ID_REQUEST = "GET_TEAM_BY_ID_REQUEST";
export const GET_TEAM_BY_ID_SUCCESS = "GET_TEAM_BY_ID_SUCCESS";
export const GET_TEAM_BY_ID_FAIL = "GET_TEAM_BY_ID_FAIL";

export const UPDATE_TEAM_BY_ID_REQUEST = "UPDATE_TEAM_BY_ID_REQUEST";
export const UPDATE_TEAM_BY_ID_SUCCESS = "UPDATE_TEAM_BY_ID_SUCCESS";
export const UPDATE_TEAM_BY_ID_FAIL = "UPDATE_TEAM_BY_ID_FAIL";
