export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST";
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const GET_USER_COUNT_BY_TEAM_REQUEST = "GET_USER_COUNT_BY_TEAM_REQUEST";
export const GET_USER_COUNT_BY_TEAM_SUCCESS = "GET_USER_COUNT_BY_TEAM_SUCCESS";
export const GET_USER_COUNT_BY_TEAM_FAIL = "GET_USER_COUNT_BY_TEAM_FAIL";

export const GET_USER_COUNT_BY_ROLE_REQUEST = "GET_USER_COUNT_BY_ROLE_REQUEST";
export const GET_USER_COUNT_BY_ROLE_SUCCESS = "GET_USER_COUNT_BY_ROLE_SUCCESS";
export const GET_USER_COUNT_BY_ROLE_FAIL = "GET_USER_COUNT_BY_ROLE_FAIL";

export const DELETE_USER_BY_ID_REQUEST = "DELETE_USER_BY_ID_REQUEST";
export const DELETE_USER_BY_ID_SUCCESS = "DELETE_USER_BY_ID_SUCCESS";
export const DELETE_USER_BY_ID_FAIL = "DELETE_USER_BY_ID_FAIL";

export const UPDATE_USER_BY_ID_REQUEST = "UPDATE_USER_BY_ID_REQUEST";
export const UPDATE_USER_BY_ID_SUCCESS = "UPDATE_USER_BY_ID_SUCCESS";
export const UPDATE_USER_BY_ID_FAIL = "UPDATE_USER_BY_ID_FAIL";
